######################################################################
# Automatically generated by qmake (2.01a) mer. oct. 10 09:11:57 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include main src
INCLUDEPATH += . include

# Input
HEADERS += include/client.h include/serveur.h \
    include/message.h
SOURCES += main/main.cpp src/client.cpp src/serveur.cpp \
    src/message.cpp

QT += network
