######################################################################
# Automatically generated by qmake (2.01a) mer. sept. 26 22:03:48 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include main src
INCLUDEPATH += . include

# Input
HEADERS += include/client.h include/serveur.h
SOURCES += main/main.cpp src/client.cpp src/serveur.cpp

QT += network